### ISSUE TITLE
Two copies of U2/U4 in the schematic

### ISSUE THREAD

**Issue by sconklin** [dkozel/noisesource-psu#2]
I'm using kicad version 5.0.2-bee76a0~ubuntu18.04.1, and it complained that the symbol for the FT230XS was out of date. I updated it, and ended up with two stacked parts in the same location, U2 and U4. I can't tell whether this is from the updated library or an error in the schematic.

U4 doesn't appear on the PCB.

**Comment by dkozel** [comment]
The use of libraries in KiCad has been one of the larger learning points. I'll double check the schematic on my side. I'm using Kicad 5.1.5 and git HEADs of the standard libraries.

**Comment by sconklin** [comment]
I think that KiCAD may use the word "older" in places where the library is newer. I need to review my library defaults as well.

**Comment by dkozel** [comment]
There was indeed a second FT230XS in the schematic. I had only used one in the layout so a quick fix.

Thanks!
